### PR TITLE
Added a 'check' operation to hubmap-docker.sh

### PR DESCRIPTION
**Pull request by jswelling**
This mod adds a 'check' operation to make sure that certain needed config files are in place before a build.

### CODE REVIEW

**Comment by yuanzhou** [comment]
@jswelling thanks a lot for adding the check operation, I like it! I noticed the entity-api config and uuid-api config are missing from the for loop so I added them.

Can you also explain what this `absent_or_newer()` does exactly? Sorry that I don't have extensive knowledge of bash scripting.

````
absent_or_newer ../ingest-ui/docker/ingest-ui/src ../ingest-ui/src/ingest-ui
absent_or_newer ../ingest-ui/docker/ingest-api/src ../ingest-ui/src/ingest-api
absent_or_newer ../uuid-api/docker/uuid-api/src ../uuid-api/src/uuid-api
absent_or_newer ../entity-api/docker/entity-api/src ../entity-api/src/entity-api
````

And we don't have the paths on the right in the above lines, ` ../ingest-ui/src/ingest-ui`, ` ../ingest-ui/src/ingest-api`, ` ../uuid-api/src/uuid-api`, `../entity-api/src/entity-api`, can you please clarify?

**Comment by jswelling** [comment]
I thought I had the cfg's for uuid-api and entity-api on lines 86 and 87- did I miss them?
absent_or_newer is a function to check for a condition where one of the src directories has been copied to under its docker directory, but then its original has been edited and the edit not copied under the docker directory.  I think this can happen because if the docker/.../src directory already exists the docker-setup.sh script will error out when the 'mkdir' command fails, and the updates will not be copied from the src directory to the docker/some-api/src directory.  The test that absent_or_newer performs asks if the docker/some-api/src directory does exist *and* if the src directory is newer.  (It's not a good check because it's really only testing the top level of the directory, but it's not useless).  If both conditions are true absent_or_newer writes an error message and causes hubmap-docker.sh to exit with an error code.

**Comment by yuanzhou** [comment]
Thanks for the explanation. I've just merged the PR with a fixe of the source src directory paths from

````
absent_or_newer ../uuid-api/docker/uuid-api/src ../uuid-api/src/uuid-api
absent_or_newer ../entity-api/docker/entity-api/src ../entity-api/src/entity-api
````
to 
````
absent_or_newer ../uuid-api/docker/uuid-api/src ../uuid-api/src
absent_or_newer ../entity-api/docker/entity-api/src ../entity-api/src
````

Since the entity-api and uuid-api are structured a bit different from ingest-api and ingest-ui.

**Comment by yuanzhou** [comment]
It's amazing what this simple line of code `if  [ \( -e $1 \) -a \( $2 -nt $1 \) ]` does.

**Pull request merged**
