### PR TITLE
NickAkhmetov/HMP-519 Update maintenance bundle to look up maintenance message from S3

### PR DESCRIPTION
**Pull request by NickAkhmetov**
This PR updates the maintenance page bundle to include the functionalities added in https://github.com/hubmapconsortium/portal-ui/pull/3364 - i.e. the maintenance page now fetches a .md file from the s3 bucket which contains the text to be displayed.

### CODE REVIEW

**Review by lchoy — APPROVED** [review]

**Comment by yuanzhou** [comment]
@lchoy and @NickAkhmetov, this is a brilliant idea! Only a very minor issue I noticed today, maybe it has been like this since the beginning. The links at the footer are all external links, but only two has that external link icon. Would you mind updating them for the sake of consistency?
Screenshot 2024-01-05 at 9 20 08 AM

**Comment by NickAkhmetov** [comment]
@yuanzhou That's an interesting question! This is the same footer we have in the rest of the data portal application, minus the links to internal pages, so this does largely match the rest of the site.

With some of these links (project website, data sharing policy, overview) I can see why we don't have an external link icon, as these are technically still HuBMAP sites. However, GitHub should probably have an external link icon by this logic.

@tsliaw, do you recall what criteria we use to determine whether to use an external link icon or not?

**Comment by NickAkhmetov** [comment]
After confirming with Tiffany,
- We will add it to the GitHub link
- We are adding it to the portal analytics link and making sure the portal analytics link appears in maintenance mode

**Comment by NickAkhmetov** [comment]
@yuanzhou It should be all set now - I rebuilt the maintenance page from the branch where I have the footer links updated: https://github.com/hubmapconsortium/portal-ui/pull/3368

Updated maintenance footer: 
294593317-a0f822bb-5f27-43e4-9f96-e6fa7bc044f2

**Comment by yuanzhou** [comment]
@NickAkhmetov thank for your attention to details!

**Review by yuanzhou — APPROVED** [review]

**Pull request merged**
